version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_password"
    ports:
      - "10051:10051"
  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_password"
                
    ports:
      - "5432:5432"    
    volumes:
      - zabbix-postgres:/var/lib/postgresql/data
  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:latest
    environment:
      DB_SERVER_HOST: "postgres-server"
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_password"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "80:8080"
 
volumes:
  zabbix-postgres: