filebeat.modules:
- module: nginx
  access:
    var.paths: ["/var/log/nginx/access.log*"]
  error:
    var.paths: ["/var/log/nginx/error.log*"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ["vm-elastics.ru-central1.internal:9200"]
  username: "elastic"
  password: "o6tWSO4KRTfQ92KcGMpE"

setup.kibana:
  host: "vm-kibana.ru-central1.internal:5601"