#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
 - name: ermac
   groups: sudo
   shell: /bin/bash
   sudo: 'ALL=(ALL) NOPASSWD:ALL'
   ssh-authorized-keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyX6zUYAskV/bduIGwvXow/zZuZCcwcenVQXDqWcPP09fSa/ZIUDThiDFCSNDBWsVttuPujidvl3jL26zJqFmZfp8WX7VjZoadZ0wixzwGgUDgRKhh6GbsnrUEZiEUy3rDVU+gx/rZp2EaAyN9wIAu9uegae92RkZb+4VuI3JZ1L4mjofUWanOacosG8eVqSEEdzmK3mrxvSfM85GTK58pQlNHRphXvhBWBsnDnQ5botloFlVLSPP6cbSE+OwxwQRJtOdb79nK4XgYOb/AoMQBEu0wfPEBVUe35fXB78wUDhJPPznuRFlkB8bNBwdye7NY7QCI+xgrhRaDxfwNOieAw55h0GsbJoZLkKf82dg+vQMWoYG9+j0Gp3dgLHezA6c75eH6wWw8EuijgplYkutWcpeJ9iq5kufJvJX7RIMC2g1stbBm3M72fc0fno3F7kwdgENDc+P6zbA3w74hzjYPe18sRMa7URdmo4WkBoffzarKBffEYQVtQAMIKUN8Aak= ermac@ubuntu-server
runcmd: []