---
- name: Установка и настройка  Elasticsearch
  hosts: elastics
  become: true
  tasks:
    - name: Add Elastic 7.x repository
      apt_repository:
       repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
       state: present
       filename: 'elastic-7.x'

    - name: обновление кэша репозитория
      apt:
        update_cache: yes  

    - name: Установка Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Копирование конфигурационного файла elasticsearch
      copy:
        src: /home/ermac/Diplom/Diplom/ansible/servers_data/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml   

    - name: Установка network.host из файла
      set_fact:
        network_host: "{{ lookup('file', '/home/ermac/Diplom/Diplom/ansible/servers_data/elastics_ip.txt') }}"

    - name: Обновление elasticsearch.yml с новым network.host
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        regexp: '^network.host:'
        line: "network.host: {{ network_host }}"
        state: present    
    

    - name: Запуск и включение службы Elasticsearch
      service:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Задание паролей для встроенных пользователей Elasticsearch
      command: >
        /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b
      register: passwords_output
      changed_when: "'PASSWORD elastic =' in passwords_output.stdout"

    - name: Вывод паролей пользователей
      debug:
        msg: "{{ passwords_output.stdout_lines }}"
  