---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ghcr.io/dandyrow/podman-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    pre_build_image: true
    command: ""
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
